version: '3'

services:
  # Servicio para PostgreSQL
  postgres:
    image: postgres:13
    container_name: sonarqube_postgres
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    networks:
      - sonarnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Servicio para SonarQube
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_WEB_PORT: "9000"
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    depends_on:
      - postgres
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always

# Definir una red interna para conectar SonarQube y PostgreSQL
networks:
  sonarnet:
    driver: bridge

# Volúmenes para persistencia de datos
volumes:
  postgres_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

